config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "homes#index"
  resources :items, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :show]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :item, counter_cache: :likes_count
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :item
  belongs_to :user
  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all 
  end

  def show
    @item = Item.find(params[:id])
    # 下の行いる？
    @items = @item.reviews.includes(:user)
    @review = Review.new
    @reviews = @item.reviews.includes(:user)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.create(user_id: current_user.id, item_id: params[:item_id])
    @likes = Like.where(item_id: params[:item_id])
    @items = Item.all
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, item_id: params[:item_id])
    like.destroy
    @likes = Like.where(item_id: params[:item_id])
    @items = Item.all
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end

  def create
    review = Review.create(review_params)
    redirect_to "/items/#{review.item.id}"
  end

  private
  def review_params
    params.require(:review).permit(:text).merge(user_id: current_user.id, item_id: params[:item_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/homes/index.html.erb
<!DOCTYPE html>
  <html>
    <div class="choose_box">
          <div class="app-theme">
            <p>おすすめボードゲーム(全5問)</p>
          </div>


    <!-- ここから５つ質問を記述 -->
          <!-- 質問1 -->
          <div id="q_01" class="fit">
            <p>質問1: あなたは普段　</p>
            <ul>
              <li><a class="btn" href="#q_02" data-value="a">話すペースが速い</a></li>
              <li><a class="btn" href="#q_02" data-value="b">話すペースがゆっくり</a></li>
            </ul>
          </div>

          <!-- 質問2 -->
          <div id="q_02" style="display: none;">
            <p>質問2:　あなたは普段、相手との会話で</p>
            <ul>
              <li><a class="btn" href="#q_03" data-value="a">間をとらずに話す</a></li>
              <li><a class="btn" href="#q_03" data-value="b">間をとりながら話す</a></li>
            </ul>
          </div>

          <!-- 質問3 -->
          <div id="q_03" style="display: none;">
            <p>質問3:　あなたの話し方は</p>
            <ul>
              <li><a class="btn" href="#q_04" data-value="a">語尾がキッパリ</a></li>
              <li><a class="btn" href="#q_04" data-value="b">語尾がソフト</a></li>
            </ul>
          </div>

          <!-- 質問4 -->
          <div id="q_04" style="display: none;">
            <p>質問4:　あなたは普段声が</p>
            <ul>
              <li><a class="btn" href="#q_05" data-value="a">大きめ</a></li>
              <li><a class="btn" href="#q_05" data-value="b">小さめ</a></li>
            </ul>
          </div>

          <!-- 質問5 -->
          <div id="q_05" style="display: none;">
            <p>質問5:　意見を求められた時、あなたは</p>
            <ul>
              <li><a class="btn end" data-value="a">自分から口火を切る</a></li>
              <li><a class="btn end" data-value="b">後から発言する</a></li>
            </ul>
          </div>



    <!-- ここから以下回答 -->
          <div id="answer_01" class="result" style="display: none;">
            <div class="result_theme ">
                  <p>あなたの性格は</p>
            </div>
            <div class="result_type0 ">
                  <h4>『イケイケどんどん』タイプ</h4>
            </div>
            <div class="result_discription0">
              <h2>めっちゃ自己主張 × めっちゃスピーディ</h2>
              <p>
                　あなたは自己主張強いのでリーダーに向いています。今すぐリーダーになろう。
              </p>
            </div>
            <div class="return-btn">
              <a class="return" href="index.html">もどる</a>
            </div>
          </div>



        <!-- 回答の答え2 -->
          <div id="answer_02" style="display: none;">
                <div class="result_theme ">
                  <p>あなたの性格は</p>
            </div>
            <div class="result_type1 ">
                  <h4>『まろやか』タイプ</h4>
            </div>
            <div class="result_discription1">
              <h2>周りを立てる人 × じっくり考える人</h2>
              <p>
                　あなたは物事をじっくり考えて、最善策を練ることが得意。組織や周りを支えることが得意。
              </p>
            </div>
            <div class="return-btn">
              <a class="return" href="index.html">もどる</a>
            </div>
        </div>
    <!-- この辺に回答を記述 -->
    </div>




      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
      <script type="text/javascript" src="test.js"></script>
    </body>
  </html>

app/views/items/index.html.erb
<div class="contents">
  <% @items.each do |item| %>
    <div class="content_post" style="background-image: url(<%= item.image %>);">
      <div class="content_list">
        <p><%= item.name %></p>
        <p><%= item.people %></p>
        <p><%= item.time %></p>
        <p><%= item.age %></p>
        <%= link_to "詳細", "/items/#{item.id}", class: "item_page" %>
      </div>
    </div>
  <% end %>
</div>

app/views/items/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="styleseet" href="game.scss">
  </head>

<div class="game">
  <div class="game_post" style="background-image: url(<%= @item.image %>);">
    <div class="game_list">
      <p><%= @item.name %></p>
      <p><%= @item.people %></p>
      <p><%= @item.time %></p>
      <p><%= @item.age %></p>
    </div>
    <div class="rule">
      <p>ストーリー・ルール</p>
      <p><%= @item.rule %></p>
      <%if user_signed_in?%>
        <div class="reviews">
          <%= link_to "レビューを投稿する", "/items/#{@item.id}/reviews/new", class: "review" %>
          <%# <%= link_to "レビューを見る", "/", class: "review_list_link" %> 
        </div>
      <% else %>
        <div class="reviews_list">
          <small>※レビュー投稿はログインすると可能になります。</small>
        </div>
      <% end %>
    </div>
  </div>
    <%# <%= video_tag("https://youtu.be/35TvEMx0NyU", :controls => true, :loop => true, :size => 20*20)%>
    <%# <a class="video__link" ontouchstart="" href="/games/madrino/videos/100"> %>
    <%# <iframe width="640" height="365" src="https://youtu.be/yGP4lCVvCO4" frameborder="0" allowfullscreen="allowfullscreen" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" class="">
    </iframe> %>
<%# ここのURLはmp４ファイルを/public/videos/mp4にして表示 %>
  <div class="game_review">
    <h4>＜レビュー＞</h4>
      <% if @reviews %>
        <% @reviews.each do |review| %>
          <p>
            <strong><%= link_to review.user.nickname, "/users/#{review.user_id}" %>：</strong>
            <%= review.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>boardgame2</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="logo">
        <a class="h1" href="/">
          <span class="image">
            <img alt="ロゴ" src="boardgame-logo.png">
          </span>
        </a>
      <ul class="menubox">
        <li class="menubox__gaelist"><a class="menu-btn" href="/items">ゲーム一覧</a></li>
      </ul>
      <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
          </div>
        <% end %>
    </header>
    <div class="main">
      <div class="mainbox">
        <%= yield %>
      </div>
    </div>
    <footer>
      <p><small>Copyright boardgame review 2020.</small></p>
    </footer>
  </body>
</html>

app/views/reviews/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="styleseet" href="review.scss">
</head>

<div class="reviewbox">
  <h1>レビュー作成</h1>
</div>

<%= form_with(model: [@item,@review], url: item_reviews_path, class: :form, local: true) do |form| %>
  <%= form.text_area :text, placeholder: :感想, class: :form__text %>
  <%= form.submit '投稿する', class: :form__btn %>
<% end %>

</html>